---
- name: Laboratorio Ansible
  hosts: docker
  gather_facts: yes

  tasks:

    - name: Mostrar el nombre del host
      debug:
        msg: "Servidor: {{ ansible_hostname }}"

    - name: Mostrar el sistema operativo
      debug:
        msg: "Sistema Operativo: {{ ansible_distribution }} {{ ansible_distribution_version }}"

    - name: Crear el directorio /tmp/ansible-demo
      file:
        path: /tmp/ansible-demo
        state: directory
        mode: '0755'

    - name: Crear el archivo info.txt
      copy:
        dest: /tmp/ansible-demo/info.txt
        content: |
          Servidor: {{ ansible_hostname }}
          Sistema Operativo: {{ ansible_distribution }} {{ ansible_distribution_version }}

    - name: Crear directorios con loop
      file:
        path: "/tmp/ansible-demo/{{ item }}"
        state: directory
        mode: '0755'
      loop:
        - logs
        - backup
        - config

    - name: Mostrar mensaje solo si es Ubuntu
      debug:
        msg: "Este servidor ejecuta Ubuntu."
      when: ansible_distribution == "Ubuntu"